const BASE_URL =
  process.env.NEXT_PUBLIC_BASE_URL ||
  (process.env.VERCEL_URL
    ? `https://${process.env.VERCEL_URL}`
    : "http://localhost:3000");

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: "#0f172a",
  viewportFit: "cover",
  colorScheme: "dark light",
  interactiveWidget: "resizes-content",
};

export const metadata = {
  title: "Rizki Ramadhan - Full Stack Developer",
  description:
    "Full Stack Developer dan Creative Digital Solutions profesional dari Indonesia. Spesialis dalam pengembangan website modern, aplikasi web, UI/UX Design, dan solusi digital yang inovatif untuk bisnis.",
  authors: [{ name: "Rizki Ramadhan" }],
  creator: "Rizki Ramadhan",
  publisher: "Rizki Ramadhan",
  category: "Web Development & Digital Solutions",
  keywords: [
    "Digital Agency",
    "Web Development",
    "Web Design",
    "UI/UX Design",
    "Creative Agency",
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "Mobile App Development",
    "E-commerce Development",
    "SEO Optimization",
    "Digital Marketing",
    "Brand Identity",
    "Logo Design",
    "Graphic Design",
    "Indonesia Digital Agency",
    "Creative Solutions",
    "Modern Web Design",
    "Responsive Design",
    "Progressive Web App",
    "React Development",
    "Next.js Development",
    "Node.js Development",
    "Database Design",
    "API Development",
    "Cloud Solutions",
    "DevOps Services",
    "Leuwiliang",
    "Kabupaten Bogor",
    "Jawa Barat",
    "Cibinong",
    "Gunung Putri",
    "Citeureup",
    "Cileungsi",
    "Jonggol",
    "Cibungbulang",
    "Parung",
    "Ciseeng",
    "Rumpin",
    "Sukaraja",
    "Tanjungsari",
    "Caringin",
    "Cijeruk",
    "Ciawi",
    "Cisarua",
    "Megamendung",
    "Caringin",
    "Cijeruk",
    "Ciawi",
    "Cisarua",
    "Megamendung",
    "Cibinong",
    "Gunung Putri",
    "Citeureup",
    "Cileungsi",
    "Jonggol",
    "Cibungbulang",
    "Parung",
    "Ciseeng",
    "Rumpin",
    "Sukaraja",
    "Tanjungsari",
  ],
  icons: {
    icon: [
      {
        url: "/favicon.ico",
        sizes: "64x64 32x32 24x24 16x16",
        type: "image/x-icon",
      },
      {
        url: "/favicon.ico",
        sizes: "16x16",
        type: "image/png",
      },
      {
        url: "/favicon.ico",
        sizes: "32x32",
        type: "image/png",
      },
      {
        url: "/favicon.ico",
        sizes: "180x180",
        type: "image/png",
      },
      {
        url: "/favicon.ico",
        sizes: "192x192",
        type: "image/png",
      },
      {
        url: "/favicon.ico",
        sizes: "512x512",
        type: "image/png",
      },
    ],
    apple: "/favicon.ico",
    shortcut: "/favicon.ico",
    appleTouchIcon: "/favicon.ico",
  },
  tags: [
    {
      name: "Rizki Ramadhan",
      content: "Full Stack Developer & Creative Digital Solutions",
    },
    {
      name: "author",
      content: "Rizki Ramadhan",
    },
    {
      name: "robots",
      content: "index, follow",
    },
    {
      name: "language",
      content: "Indonesian, English",
    },
  ],
  manifest: "/manifest.json",
  metadataBase: new URL(BASE_URL),
  canonical: BASE_URL,
  other: {
    "mobile-web-app-capable": "yes",
    "apple-mobile-web-app-capable": "yes",
    "format-detection": "telephone=no",
    "apple-mobile-web-app-status-bar-style": "black-translucent",
    "msapplication-TileColor": "#0f172a",
    "application-name": "Rizki Ramadhan",
    "msapplication-tap-highlight": "no",
    "theme-color": "#0f172a",
    "msvalidate.01": `${process.env.NEXT_PUBLIC_BING_VERIFICATION}`,
    "google-site-verification": `${process.env.NEXT_PUBLIC_GOOGLE_SEARCH_CONSOLE_ID}`,
  },
  openGraph: {
    type: "website",
    title: "Rizki Ramadhan - Full Stack Developer & Creative Digital Solutions",
    description:
      "Full Stack Developer dan Creative Digital Solutions profesional dari Indonesia. Spesialis dalam pengembangan website modern, aplikasi web, UI/UX Design, dan solusi digital yang inovatif untuk bisnis.",
    url: BASE_URL,
    siteName: "Rizki Ramadhan",
    locale: "id_ID",
    images: [
      {
        url: "/desktop.png",
        width: 1200,
        height: 630,
        alt: "Rizki Ramadhan - Full Stack Developer & Creative Digital Solutions",
        type: "image/jpeg",
      },
      {
        url: "/desktop.png",
        width: 600,
        height: 600,
        alt: "Rizki Ramadhan Logo",
        type: "image/jpeg",
      },
      {
        url: "/desktop.png",
        width: 800,
        height: 600,
        alt: "Rizki Ramadhan Mobile Preview",
        type: "image/jpeg",
      },
    ],
    countryName: "Indonesia",
    emails: ["hallo@rizkiramadhan.web.id"],
    phoneNumbers: ["+62-813-9863-2939"],
    streetAddress: "Leuwiliang, Kabupaten Bogor, Jawa Barat",
    postalCode: "16640",
    locality: "Leuwiliang",
    region: "Jawa Barat",
    country: "ID",
    profile: {
      firstName: "Rizki",
      lastName: "Ramadhan",
      username: "rizki_ramadhan",
      gender: "male",
    },
    article: {
      publishedTime: "2024-01-01T00:00:00+07:00",
      modifiedTime: new Date().toISOString(),
      section: "Web Development & Digital Solutions",
      tags: [
        "Full Stack Developer",
        "Web Development",
        "Creative Design",
        "Technology",
      ],
    },
    video: {
      url: "https://www.youtube.com/watch?v=uURhi3S5qEM",
      type: "video/mp4",
      width: 1280,
      height: 720,
    },
    audio: {
      url: `${BASE_URL}/audio-preview.mp3`,
      type: "audio/mpeg",
    },
    // New fields
    business: {
      name: "Rizki Ramadhan",
      type: "Full Stack Developer",
      category: "Technology",
      founded: "2024",
      employees: "1-10",
      revenue: "100K-1M",
    },
    organization: {
      name: "Rizki Ramadhan",
      url: BASE_URL,
      logo: `${BASE_URL}/favicon.ico`,
      sameAs: [
        "https://www.facebook.com/rizki.ramadhan.419859",
        "https://github.com/Rizkiramadhan20",
        "https://www.instagram.com/rzkir.20",
        "https://www.tiktok.com/@rzkir.20",
        "https://www.linkedin.com/in/rizki-ramadhan12",
        "https://www.youtube.com/@codingwithrizki",
      ],
    },
  },
  twitter: {
    card: "summary_large_image",
    title: "Rizki Ramadhan - Full Stack Developer & Creative Digital Solutions",
    description:
      "Full Stack Developer dan Creative Digital Solutions profesional dari Indonesia. Spesialis dalam pengembangan website modern, aplikasi web, UI/UX Design, dan solusi digital yang inovatif untuk bisnis.",
    creator: "@codingwithrizki",
    site: "@codingwithrizki",
    images: ["/twitter-image-main.jpg", "/twitter-image-square.jpg"],
    // New Twitter fields
    app: {
      name: "Rizki Ramadhan",
      id: {
        iphone: "rizki-ramadhan-app",
        ipad: "rizki-ramadhan-app",
        googleplay: "com.rizkiramadhan.app",
      },
      url: {
        iphone: "https://apps.apple.com/app/rizki-ramadhan",
        ipad: "https://apps.apple.com/app/rizki-ramadhan",
        googleplay:
          "https://play.google.com/store/apps/details?id=com.rizkiramadhan.app",
      },
    },
  },
  // New social media metadata
  facebook: {
    appId: process.env.NEXT_PUBLIC_FACEBOOK_APP_ID,
    pages: ["rizki.ramadhan.419859"],
    admins: ["rizki.ramadhan.419859"],
  },
  instagram: {
    username: "rzkir.20",
    site: "https://www.instagram.com/rzkir.20",
  },
  linkedin: {
    company: "rizki-ramadhan12",
    site: "https://www.linkedin.com/in/rizki-ramadhan12",
  },
  youtube: {
    channel: "UC-codingwithrizki",
    site: "https://www.youtube.com/@codingwithrizki",
  },
  tiktok: {
    username: "rzkir.20",
    site: "https://www.tiktok.com/@rzkir.20",
  },
  github: {
    username: "Rizkiramadhan20",
    site: "https://github.com/Rizkiramadhan20",
  },
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SEARCH_CONSOLE_ID,
    googleTagManager: process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID,
    bing: process.env.NEXT_PUBLIC_BING_VERIFICATION,
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large" as const,
      "max-snippet": -1,
    },
    // New robots fields
    bingbot: {
      index: true,
      follow: true,
      "max-snippet": -1,
    },
    yandex: {
      index: true,
      follow: true,
    },
  },
  alternates: {
    canonical: BASE_URL,
    languages: {
      "id-ID": BASE_URL,
      "en-US": `${BASE_URL}/en`,
    },
  },
  // New structured data
  structuredData: {
    organization: {
      "@context": "https://schema.org",
      "@type": "Organization",
      name: "Rizki Ramadhan",
      url: BASE_URL,
      logo: `${BASE_URL}/favicon.ico`,
      description:
        "Full Stack Developer dan Creative Digital Solutions profesional dari Indonesia",
      address: {
        "@type": "PostalAddress",
        streetAddress: "Leuwiliang, Kabupaten Bogor, Jawa Barat",
        addressLocality: "Leuwiliang",
        addressRegion: "Jawa Barat",
        postalCode: "16640",
        addressCountry: "ID",
      },
      contactPoint: {
        "@type": "ContactPoint",
        telephone: "+62-813-9863-2939",
        contactType: "customer service",
        email: "hallo@rizkiramadhan.web.id",
      },
      sameAs: [
        "https://www.facebook.com/rizki.ramadhan.419859",
        "https://github.com/Rizkiramadhan20",
        "https://www.instagram.com/rzkir.20",
        "https://www.tiktok.com/@rzkir.20",
        "https://www.linkedin.com/in/rizki-ramadhan12",
        "https://www.youtube.com/@codingwithrizki",
      ],
    },
    website: {
      "@context": "https://schema.org",
      "@type": "WebSite",
      name: "Rizki Ramadhan",
      url: BASE_URL,
      description: "Full Stack Developer & Creative Digital Solutions",
      publisher: {
        "@type": "Organization",
        name: "Rizki Ramadhan",
      },
    },
    localBusiness: {
      "@context": "https://schema.org",
      "@type": "LocalBusiness",
      name: "Rizki Ramadhan",
      description: "Full Stack Developer & Creative Digital Solutions",
      url: BASE_URL,
      telephone: "+62-813-9863-2939",
      email: "hallo@rizkiramadhan.web.id",
      address: {
        "@type": "PostalAddress",
        streetAddress: "Leuwiliang, Kabupaten Bogor, Jawa Barat",
        addressLocality: "Leuwiliang",
        addressRegion: "Jawa Barat",
        postalCode: "16640",
        addressCountry: "ID",
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: "-6.5614",
        longitude: "106.6322",
      },
      openingHours: "Mo-Fr 09:00-18:00",
      priceRange: "$$",
    },
  },
  headers: {
    "X-Frame-Options": "DENY",
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
    "X-DNS-Prefetch-Control": "on",
    "X-XSS-Protection": "1; mode=block",
  },
  analytics: {
    googleAnalytics: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
    googleTagManager: process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID,
  },
};

export default metadata;
